### PR TITLE
Reimplement the "goto next free layer" button

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by TheBearodactyl** [comment]
this also fixes #322 btw

**Comment by TheBearodactyl** [comment]
forgot to make it a draft pr since the pr i made on the bindings repo needs to be accepted first

**Comment by TheBearodactyl** [comment]
nvm

**Comment by HJfod** [comment]
Gonna make a few changes for the released version to match the patterns used in other features, but thank you!

**Comment by TheBearodactyl** [comment]
> Gonna make a few changes for the released version to match the patterns used in other features, but thank you!

np :D

**Pull request merged**
